name: Test Build

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 选择 Java 版本
          distribution: 'temurin'  # 选择 Java 分发版本

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          # 查找并移动 APK 文件
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4  # 更新到 v4 版本
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*  # 上传 APK 文件
